namespace eval ::aloupe {
  ::msgcat::mcset de {Loupe} {Lupe}
  ::msgcat::mcset de {To clipboard} {Zu Zwischenablage}
  ::msgcat::mcset de {Save} {Speichern}
  ::msgcat::mcset de {Close} {Schließen}
  ::msgcat::mcset de {Size} {Größe}
  ::msgcat::mcset de {Zoom} {Zoom}
  ::msgcat::mcset de {Color of Image} {Farbe des Bildes}
  ::msgcat::mcset de {Save the Loupe} {Bild speichern}
  ::msgcat::mcset de "Click the magnified image\nto get a pixel's color.\n\nThen hit this button." "Klicken Sie auf das Bild, um die Farbe des Pixels zu erhalten.\n\nDrücken Sie dann diesen Knopf."
  ::msgcat::mcset de "Click, then drag and drop\nthe loupe to get the image." "Haken Sie die Lupe mit der Maus und ziehen Sie sie über den Bildschirm.\n\nWenn Sie die Maus loslassen, erhalten Sie ein vergrößertes Bild."
}
