namespace eval ::aloupe {
  ::msgcat::mcset es {Loupe} {Lupa}
  ::msgcat::mcset es {To clipboard} {A portapapeles}
  ::msgcat::mcset es {Save} {Guardar}
  ::msgcat::mcset es {Close} {Cerrar}
  ::msgcat::mcset es {Size} {Tamaño}
  ::msgcat::mcset es {Zoom} {Zoom}
  ::msgcat::mcset es {Pause} {Pausa}
  ::msgcat::mcset es {Color of Image} {Color de imagen}
  ::msgcat::mcset es {Save the Loupe} {Guardar la imagen}
  ::msgcat::mcset es "Click the magnified image\nto get a pixel's color.\n\nThen hit this button." "Haga clic en la imagen magnificada\npara obtener el color de un píxel.\n\nLuego presione este botón."
  ::msgcat::mcset es "Click, then drag and drop\nthe loupe to get the image." "Haga clic, luego arrastre y suelte\n\nla loupe para obtener la imagen."
}
