namespace eval ::aloupe {
  ::msgcat::mcset ru {Loupe} {Лупа}
  ::msgcat::mcset ru {To clipboard} {В буфер}
  ::msgcat::mcset ru {Save} {Сохранить}
  ::msgcat::mcset ru {Close} {Закрыть}
  ::msgcat::mcset ru {Size} {Размер}
  ::msgcat::mcset ru {Zoom} {Масштаб}
  ::msgcat::mcset ru {Pause} {Пауза}
  ::msgcat::mcset ru {Save the Loupe} {Сохранить изображение}
  ::msgcat::mcset ru "Click the magnified image\nto get a pixel's color.\n\nThen hit this button." "Кликните по картинке,\nчтобы получить цвет пиксела.\n\nПотом жмите эту кнопку."
  ::msgcat::mcset ru "Click, then drag and drop\nthe loupe to get the image." "Зацепите лупу мышкой и тащите её по экрану.\n\nКогда отпустите мышку, получите увеличенное изображение."
}
