namespace eval ::aloupe {
  ::msgcat::mcset ua {Loupe} {Лупа}
  ::msgcat::mcset ua {To clipboard} {До буферу}
  ::msgcat::mcset ua {Save} {Зберегти}
  ::msgcat::mcset ua {Close} {Закрити}
  ::msgcat::mcset ua {Size} {Розмір}
  ::msgcat::mcset ua {Zoom} {Масштаб}
  ::msgcat::mcset ua {Save the Loupe} {Зберегти зображення}
  ::msgcat::mcset ua "Click the magnified image\nto get a pixel's color.\n\nThen hit this button." "Кликнить по картинці,\nщоб одержати колір піксела.\n\nПотім натиснить цю кнопку."
  ::msgcat::mcset ua "Click, then drag and drop\nthe loupe to get the image." "Зачепить лупу мишею та тягніть ії по екрану.\n\nКоли відпустите мишу, одержите збільшене зображення."
}
