namespace eval ::aloupe {
  ::msgcat::mcset uk {Loupe} {Лупа}
  ::msgcat::mcset uk {To clipboard} {До буферу}
  ::msgcat::mcset uk {Save} {Зберегти}
  ::msgcat::mcset uk {Close} {Закрити}
  ::msgcat::mcset uk {Size} {Розмір}
  ::msgcat::mcset uk {Zoom} {Масштаб}
  ::msgcat::mcset uk {Pause} {Пауза}
  ::msgcat::mcset uk {Color of Image} {Колір зображення}
  ::msgcat::mcset uk {Save the Loupe} {Зберегти зображення}
  ::msgcat::mcset uk "Click the magnified image\nto get a pixel's color.\n\nThen hit this button." "Кликнить по картинці,\nщоб одержати колір піксела.\n\nПотім натиснить цю кнопку."
  ::msgcat::mcset uk "Click, then drag and drop\nthe loupe to get the image." "Зачепить лупу мишею та тягніть ії по екрану.\n\nКоли відпустите мишу, одержите збільшене зображення."
}
