#! /usr/bin/env tclsh
###########################################################
# Name:    img.tcl
# Author:  Alex Plotnikov  (aplsimple@gmail.com)
# Date:    07/03/2021
# Brief:   Handles images for alited.tcl (base64).
# License: MIT.
###########################################################

# _________________________ proc/method "red bars" ________________________ #

namespace eval img {

set _AL_IMG(0) {iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUAAAAAtv86+l98AAAAAXRS
TlMAQObYZgAAABRJREFUCNdjwAT//zM0MAIRiIEBAHh/BP9K+QllAAAAAElFTkSuQmCC}

set _AL_IMG(1) {iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAgMAAABinRfyAAAACVBMVEUAAAAAtv/tHCS5r+j6AAAA
AXRSTlMAQObYZgAAABdJREFUCNdjwA9CgYAhg4GBEUxAuHgBAIyVA3uaLu15AAAAAElFTkSuQmCC}

set _AL_IMG(2) {iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAgMAAABinRfyAAAACVBMVEUAAAAAtv/tHCS5r+j6AAAA
AXRSTlMAQObYZgAAABdJREFUCNdjwA9CgYAhq4GBEUxAuHgBALW7BH+TzwWIAAAAAElFTkSuQmCC}

set _AL_IMG(3) {iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAgMAAABinRfyAAAACVBMVEUAAAAAtv/tHCS5r+j6AAAA
AXRSTlMAQObYZgAAABdJREFUCNdjwA9CgYAhawUDI5iAcPECAMJjBM+vW7PvAAAAAElFTkSuQmCC}

set _AL_IMG(4) {iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAgMAAABinRfyAAAACVBMVEUAAAAAtv/tHCS5r+j6AAAA
AXRSTlMAQObYZgAAABdJREFUCNdjwA9CgYAha1UDI5iAcPECAOqFBdNjIsJTAAAAAElFTkSuQmCC}

set _AL_IMG(5) {iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAgMAAABinRfyAAAACVBMVEUAAAAAtv/tHCS5r+j6AAAA
AXRSTlMAQObYZgAAABdJREFUCNdjwA9CgYAha9UKRjAB4eIFAPbdBiPyKo3yAAAAAElFTkSuQmCC}

set _AL_IMG(6) {iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAgMAAABinRfyAAAACVBMVEUAAAAAtv/tHCS5r+j6AAAA
AXRSTlMAQObYZgAAABdJREFUCNdjwA9CgYAha9WqRjAB4eIFAB4KBycPp4bQAAAAAElFTkSuQmCC}

set _AL_IMG(7) {iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAgMAAABinRfyAAAACVBMVEUAAAAAtv/tHCS5r+j6AAAA
AXRSTlMAQObYZgAAABdJREFUCNdjwA9CgYAha9WqlWACwsULACoSB3dYfX36AAAAAElFTkSuQmCC}

# ________________________ Tcl files _________________________ #

set _AL_IMG(Tcl) {iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAG1BMVEUAAABEebIcVpN6oMOFqMp5
nsLb////SUlJbZK4hOm9AAAABnRSTlMA4bzy7uoa1GpmAAAAPklEQVQI12NgdgGCBgYGBtY0IMgA
MpjTQKABJAIWgomkCQBFIAwSRdLL08vKwCJl6WkgBiuQUVaOokYJDAQAbKolE+c3DpQAAAAASUVO
RK5CYII=}

# ________________________ e_menu _________________________ #

set _AL_IMG(e_menu) {iVBORw0KGgoAAAANSUhEUgAAABYAAAAcCAMAAABS8b9vAAAAD1BMVEUrRF3Y2tab4+U9Oz4jKjDz
nD2xAAAAP0lEQVQoz2NgwgoYmBiwAKKEGaEAXZgFDLAIM2ITxm4IcS5hRANgYSYmRkYUL+IVxmEI
1VyCohav8PByCVYAAFFEAcBPpMHrAAAAAElFTkSuQmCC}

# ________________________ keyboard ("key") _________________________ #

set _AL_IMG(kbd) {iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABAlBMVEUAAAAQEBZ9fZsYGCF/f5oa
GiF/f52AgJ13d5RnZ4l5eZgaGiISEhcNDRCGhqKLi6V7e5pvb45hYYVRUWc5OVMSEhsICAg6OmoZ
GSUBAQUAAADg4Onn5+7k5OzZ2eWFhalubpb6+vx+fqnb2+XCwtLX1+HR0d7NzdvExNXw8PfW1uDT
0963t8W0tMOxscH////r6/Hp6fHm5u7d3ea/v8+rq72oqLicnLCYmK9wcIX29vzt7fbt7fPi4uzg
4OvW1uTJydrGxta9vdXFxdG9vcq4uMq1tce4uMacnMGWlsCRkbShobKAgKyUlKiQkKaMjJ1xcZuG
hpZ9fZJnZ5J6eotOTmdxldK8AAAAG3RSTlMAuPnA+sD5+/v7+cW7nfz7+/v71dOrko8lIxvPqped
AAAAt0lEQVQY0z3O1XbCQBRA0dtpmra424RgYYjg7u6u//8r3GEx7MfzdADChMhElgmRJMntjwLY
svXWotmYaIgVnQCu2rJzuOzGuq5rbO4A+K02jte7xnJIXX1hqLQKp45pWpbFaB6DVK2zWV7NIjPO
g0ehNTrMvFQKGGxl+tHj4a+vxAWjyINRVoQuD16jlBJKTQz/I6q+ZQZtHvRtQpjy4Fvv08ImgeuB
W/Lj/AgBRIL2b+4H2Z2xJ1dcH5DXF1JFAAAAAElFTkSuQmCC}

# ________________________ Tcl & alited _________________________ #

set _AL_IMG(feather) {iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAh1BMVEX/////SUnrPkHNFB3uSEvb
JCTmO0LjLTPeMTnOFyLpOjzUGSToMzfUICr99fjsREfdLTfXJS7eJCr/+fnkNz7sQkP3//raKDTg
Jy3LDxfkQEfeQUThOEHaNzraHiX+8fHYGyLVFR3GChL7/vffMz/kMzvnRFTbKy7MISnREBjABQ3V
RUnNKUVaFHpTAAABaElEQVQ4y43RiW6DMBAE0DFgYggNR07OEpLmav//+7q7HBaiijpIsYWfBwfw
euU5cgR0udCu++O6gcuR365D5wIXjQcelwAGWtbWfQJC6HKtL5BoaCLGiPngBEGA53kNyeFwICBX
kug0PaZpSgL5mbo0AYXD1KIHQCUCQNlsBnITknCORwLPtm2bLPsGR01nqeurMYYIzk3TZIAt6UlZ
VtfrziQJ2izLTve7Wa2w3UqHpEbh+9XOGDQMaLUPd0hJiRuD3Q60yvnyfb+056CuoqAOAidejSKa
USax4SFWtIuAMVEY+lWl6nrqEFAoxYC2E3SUUrZjGDhY0XY1xHGcWP6u+hMsOhQEhLwv9pRV/EI+
JxARiD1v1kFAJj1w9ntPgA0BEQJC2287+AkLMMsMeIv1ecPeApsNRgFHGpaBBeN0Gv4HlAVM+jvK
DpR3wApnAHzQ2ZMkI4jlxhyMYo/QfotlSCKK3gr1C7uEFe1NRJ3HAAAAAElFTkSuQmCC}

set _AL_IMG(ale) {iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAclBMVEX/////SUnOFR7rPkHbJCTu
SEvmO0LVGSPjLTPYJjDfJSvsQ0XeMTnkNj3pOjzUICr5//r99fjoMzfdLTf/+fnLDxfkQEfeQUTh
OEHaNzraHiX+8fHVFR3GChLfMz/nRFTbKy7MISnREBjABQ3VRUnNKUWO7K/eAAABUElEQVQ4y5WR
226DMBAFz4IhKRhKIFwbyK39/1/s7mJwiVCkjh9iybODA3g+6xo1Al0mCH6Cv4wjxgAoDO64FwEs
K8JhRrYYa2MKKIaXhbXqfAoiPC4HKEVRwMyrqsyHwgbqC7cMAEKxVowTOKICmNPJKVdVKkEMPDgw
JMk3BFrv0veTtZYVXIZhSAAfmZW27aYps1WFQ8LcbvZ4xPmsDaVHE8ddZi0GEfh0RhoaaXEVIcvA
p0IWx3Hr78GtpuGGCHJalrxbIC2BkBJPsWBtmedx11Hfu4YTGiIReJzFkIh8w/0IOPI4OcIwTPXv
0r7w2iCokMtcGpG35IV8rULJQhpFmwYLupkFGVfBo690EXLf9w15wp7g2Qi+7yPvBOWExUC47uCm
582/BAo3As28LShbISIp8QI2jXB5RBStAq28CC4peCPl5S65L/iPtQ/oF2i8Eez07AzcAAAAAElF
TkSuQmCC}

}
# _________________________________ EOF _________________________________ #
#RUNF1: alited.tcl DEBUG
