#! /usr/bin/env tclsh
# _______________________________________________________________________ #
#
# The list of alited's localized messages.
# _______________________________________________________________________ #


namespace eval ::alited {

  set al(MC,about)       [msgcat::mc "About"]
  set al(MC,nofile)      [msgcat::mc "No name"]
  set al(MC,error)       [msgcat::mc "Error"]
  set al(MC,warning)     [msgcat::mc "Warning"]
  set al(MC,question)    [msgcat::mc "Question"]
  set al(MC,select)      [msgcat::mc "Select"]  ;# verb "to select"
  set al(MC,notsaved)    [msgcat::mc "\"%f\" wasn't saved.\n\nSave it?"]
  set al(MC,saving)      [msgcat::mc "Saving"]
  set al(MC,saveas)      [msgcat::mc "Save as"]
  set al(MC,files)       [msgcat::mc "Files"]
  set al(MC,line)        [msgcat::mc "Line"]
  set al(MC,moveup)      [msgcat::mc "Move Up"]
  set al(MC,movedown)    [msgcat::mc "Move Down"]
  set al(MC,FavLists)    [msgcat::mc "Lists of Favorites"]
  set al(MC,swfiles)     [msgcat::mc "Switch to Unit Tree"]
  set al(MC,swunits)     [msgcat::mc "Switch to File Tree"]
  set al(MC,filesadd)    [msgcat::mc "Create File"]
  set al(MC,filesadd2)   [msgcat::mc "Enter a name of file to create in:\n%d\n\nIf it is a directory, check 'Directory' checkbox.\nThe directory can include subdirectories (a/b/c)."]
  set al(MC,filesdel)    [msgcat::mc "Delete File"]
  set al(MC,unitsadd)    [msgcat::mc "Add Unit"]
  set al(MC,unitsdel)    [msgcat::mc "Remove Unit(s)"]
  set al(MC,favoradd)    [msgcat::mc "Add to Favorites"]
  set al(MC,favordel)    [msgcat::mc "Remove from Favorites"]
  set al(MC,nosels)      [msgcat::mc "No item selected."]
  set al(MC,updtree)     [msgcat::mc "Update Tree"]
  set al(MC,moving)      [msgcat::mc "Moving"]
  set al(MC,movefile)    [msgcat::mc "Move %f\nto\n%d\n?"]
  set al(MC,introln1)    [msgcat::mc "First Lines"]
  set al(MC,introln2)    [msgcat::mc "Can't touch the first %n lines."]
  set al(MC,favorites)   [msgcat::mc "Favorites"]
  set al(MC,addfavor)    [msgcat::mc "Add \"%n\" of %f\nto the favorites?"]
  set al(MC,addexist)    [msgcat::mc "Item \"%n\" of %f\nis already in the favorites."]
  set al(MC,delfavor)    [msgcat::mc "Remove \"%n\" of %f\nfrom the favorites?"]
  set al(MC,selfavor)    [msgcat::mc "Select \"%t\""]
  set al(MC,copydecl)    [msgcat::mc "Copy Declaration"]
  set al(MC,delitem)     [msgcat::mc "Remove \"%n\"\nfrom \"%f\"?"]
  set al(MC,delfile)     [msgcat::mc "Delete \"%f\"?"]
  set al(MC,tpl)         [msgcat::mc "Templates"]
  set al(MC,tpl1)        [msgcat::mc "Use buttons on the right to add/change/delete a template."]
  set al(MC,tpl2)        [msgcat::mc "In its text, set the cursor where it should be in the editor."]
  set al(MC,tpl3)        [msgcat::mc "Templates' list:"]
  set al(MC,tpl4)        [msgcat::mc "Current template:"]
  set al(MC,tpl5)        [msgcat::mc "New template:"]
  set al(MC,tpladd)      [msgcat::mc "Add a template"]
  set al(MC,tplchg)      [msgcat::mc "Change a template"]
  set al(MC,tpldel)      [msgcat::mc "Delete a template"]
  set al(MC,tplsel)      [msgcat::mc "Select a template"]
  set al(MC,tplnew)      [msgcat::mc "The template #%n added"]
  set al(MC,tplupd)      [msgcat::mc "The template #%n updated"]
  set al(MC,tplrem)      [msgcat::mc "The template #%n removed"]
  set al(MC,tplent1)     [msgcat::mc "Enter a name of the template"]
  set al(MC,tplent2)     [msgcat::mc "Enter a text of the template"]
  set al(MC,tplexists)   [msgcat::mc "This template already exists"]
  set al(MC,tplerrsav)   [msgcat::mc "This templates not saved to\n\"%f\"."]
  set al(MC,tplloc)      [msgcat::mc "Place after:"]
  set al(MC,tplloc1)     [msgcat::mc "line"]
  set al(MC,tplloc2)     [msgcat::mc "unit"]
  set al(MC,tplloc3)     [msgcat::mc "cursor"]
  set al(MC,tpldelq)     [msgcat::mc "Delete a template #%n ?"]
  set al(MC,errcopy)     [msgcat::mc "Can't copy \"%f\" to\n\"%d\""]
  set al(MC,removed)     [msgcat::mc "\"%f\" removed to \"%d\""]
  set al(MC,filename)    [msgcat::mc "File name:"]
  set al(MC,directory)   [msgcat::mc "Directory"]
}
# _________________________________ EOF _________________________________ #
#RUNF1: alited.tcl
